[tools]
python = "3.13"
uv = "latest"
jq = 'latest'
node = "25"
aws-cli = "latest"
aws-vault = "latest"
gcloud = "latest"
"npm:aws-cdk" = "latest"
bun = "latest"
golang = "latest"

[env]
_.file = ['.env.1password']
_.python.venv = { path = ".venv", create = true, uv_create_args = ['--seed']}
DEV_ENV="{{env.HOME}}/repos/personal/dotfiles"


[tasks.install-deps]
description = "install dependencies"
run = [
    "uv pip install -r requirements.txt",
    "git secrets --install",
    "git secrets --register-aws",
    "detect-secrets scan > .secrets.baseline",
]

