#!/usr/bin/env bash

# File system
alias g='git'
alias ls='eza -lh --group-directories-first --icons=auto'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'


alias nsmi=nvidia-smi
alias v=aws-vault
alias cb="xclip -sel clip"

# Scripts execution
alias cedit="claude --permission-mode acceptEdits --disallowTools Bash"
