-- Colorscheme spec generated by `omarchy theme set` from the template in
-- omarchy/themed/neovim.lua.tpl. Absent on non-Omarchy machines.
local generated = vim.fn.expand("~/.local/state/omarchy/current/theme/neovim.lua")

if not vim.loop.fs_stat(generated) then
    return {}
end

return dofile(generated)
