-- Colorscheme spec generated by `omarchy theme set` from the template in
-- omarchy/themed/neovim.lua.tpl. Absent on non-Omarchy machines.
local generated = vim.fn.expand("~/.local/state/omarchy/current/theme/neovim.lua")

if not vim.loop.fs_stat(generated) then
    return {}
end

-- The template targets LazyVim and names the colorscheme through a
-- `LazyVim/LazyVim` spec. Keeping that entry would drag LazyVim into this
-- non-LazyVim config and trip its import-order check, so take the name and
-- drop it; lazy/colors.lua reads it back out of vim.g.
local spec = {}
for _, plugin in ipairs(dofile(generated)) do
    if plugin[1] == "LazyVim/LazyVim" then
        vim.g.omarchy_colorscheme = plugin.opts and plugin.opts.colorscheme
    else
        -- Load ahead of the specs that call ColorMyPencils().
        plugin.lazy = false
        plugin.priority = 1000
        table.insert(spec, plugin)
    end
end

return spec
